global using MagicT.Shared.Models;
global using MagicT.Shared.Models.ViewModels;
global using MagicT.Web.Shared.Pages.Authorization;
global using MagicT.Web.Shared.Base;
global using MagicT.Shared.Services;
global using Generator.Components.Components;
global using Bromix.MudBlazor.MaterialDesignIcons;
global using MagicT.Client.Hubs;
global using MagicT.Shared.Hubs;
global using Microsoft.AspNetCore.Components.Routing;
using MagicT.Redis.Models;
using Microsoft.AspNetCore.Components;